### ISSUE TITLE
run on linux 

### ISSUE THREAD

**Issue by nehcgnay** [jacoblevine/PhenoGraph#1]
Hello, 

I would like to run phenograph on linux but the executable files in louvain folder are not compatible.  
I also tried compiling them from the source code downloaded here https://sites.google.com/site/findcommunities/.
However, the compiled files are not working, and the process is stacked at "Running Louvain modularity optimization". Am I using wrong code of this lib?
Thanks!

Best/ Yang

**Comment by jacoblevine** [comment]
Hi Yang,

Apologies that a version for Linux has lagged behind Mac and Windows. Thanks for trying to solve the problem yourself. Your idea to recompile the Louvain source was a good one, but PhenoGraph works with a modified version of that code, which improves runtime. In the worst case I can provide you with that modified code to compile on your machine. However, I have also just updated the package (Version 1.2) to include compiled Linux binaries that will hopefully solve the problem. Please give it a try and let me know if it works.

Thanks,
Jacob

**Comment by nehcgnay** [comment]
It's working perfect! Thanks a lot Jacob!
