### ISSUE TITLE
Is it possible to set a seed?

### ISSUE THREAD

**Issue by DenisSch** [jacoblevine/PhenoGraph#14]
Is it possible to set a seed so that the results are reproducible?

https://github.com/BodenmillerGroup/histoCAT/issues/14

**Comment by prubbens** [comment]
This would indeed be a valuable addition to the algorithm.

**Comment by DenisSch** [comment]
I have pushed a version for MacOS to https://github.com/BodenmillerGroup/histoCAT/commit/8d74a318764e83408b648a61465c5140749ca835
