### ISSUE TITLE
parallel computing issue 

### ISSUE THREAD

**Issue by nehcgnay** [jacoblevine/PhenoGraph#2]
Hello, 

I am trying to use the parallel computing function. 
I called phenograph.cluster in ipython notebook. It gives the following error when use_parallel is set True:

```
Launching new cluster with 8 workers
Cluster launched successfully
---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)<string> in <module>()
TypeError: 'CannedFunction' object is not callable
```

I also tried to set dview. But it gives another error:

```
Neighbors computed in 0.06748223304748535 seconds
---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<string> in <module>()
/envs/py34/lib/python3.4/site-packages/ipyparallel/util.py in _pull(keys)
    264         return [eval(key, globals()) for key in keys]
    265     else:
--> 266         return eval(keys, globals())
    267 
    268 @interactive
<string> in <module>()
NameError: name 's' is not defined
```

Any suggestion?

Thank you in advance!

Best,
Yang

**Comment by jacoblevine** [comment]
Hi Yang,

I'm sorry for the delay in getting back to you; in fact I only just saw that you opened this issue.

Hopefully it is resolved by the latest commit. I have completely eliminated the dependency on IPython/ipyparallel for CPU parallelization, which is now handled by Python's multiprocessing package.

Please let me know if you still encounter problems.

Best,
Jacob

**Comment by nehcgnay** [comment]
Thanks a lot Jacob!
