### ISSUE TITLE
Is this repo deprecated?

### ISSUE THREAD

**Issue by scottgigante** [jacoblevine/PhenoGraph#23]
It appears this repository is outdated compared to the fork https://github.com/dpeerlab/PhenoGraph . The fork contains more up to date installation information (addressing, for example, #20) and has an updated codebase. 

@armMSKCC @hisplan is your fork now the preferred access point for this repository? In that case it would be best if this one contains a clear marker in the readme that it is out of date.

**Comment by hisplan** [comment]
Hi,

README.md has been updated. And yes, https://github.com/dpeerlab/PhenoGraph is the one that we're trying to actively maintain.

Thanks.
