### ISSUE TITLE
New computer, new error message

### ISSUE THREAD

**Issue by AbbyKimball** [jacoblevine/PhenoGraph#7]
I recently got the newest mac and ever since this I have had an issue opening the heat map in shiny app, I get the error: "cannot open file 'cytofkit_shinyAPP_marker_heatmap_plot.pdf" I have tried loading the data into the shiny app on other computers, and it has worked. This has also occured with three different data sets. Thanks!

**Comment by jacoblevine** [comment]
Hi @AbbyKimball, it sounds like you are using a different software package, specifically, [this one](https://github.com/JinmiaoChenLab/cytofkit). Please contact them.
